### ISSUE TITLE
Cannot convert NaN to integer

### ISSUE THREAD

**Issue by Markdood88** [psychoinformatics-de/remodnav#42]
remodnav "test.tsv" "output.tsv" .01855812 1000.0
Traceback (most recent call last):
  File "c:\users\user\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\anaconda3\Scripts\remodnav.exe\__main__.py", line 7, in <module>
  File "c:\users\user\anaconda3\lib\site-packages\remodnav\__init__.py", line 145, in main
    pp = clf.preproc(
  File "c:\users\user\anaconda3\lib\site-packages\remodnav\clf.py", line 855, in preproc
    data['x'][mask] = np.nan
ValueError: cannot convert float NaN to integer

**Comment by Markdood88** [comment]
test.tsv is a 54000 row, 2 column file with x and y values from -2500 -> 2500 if this helps. Im not sure what this error is in reference to.

**Comment by adswa** [comment]
Hey, do you still have problems with this? I'm closing this issue due to inactivity and missing information, so that I can reduce the number of open issues a bit - but please feel free to reopen this in case there are remaining problems or questions :)
